### ISSUE TITLE
Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

### ISSUE THREAD

**Issue by swest** [danielgtaylor/atom-monokai-extended#5]
In index.less: Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

Atom 0.186.0
monaki-extended 0.2.2

**Comment by case** [comment]
+1

**Comment by danielgtaylor** [comment]
Closing in favor of #4, which seems to be about the same issue.
